site_name: MkDocs Exporter
site_url: https://adrienbrignon.github.io/mkdocs-exporter
repo_url: https://github.com/adrienbrignon/mkdocs-exporter
repo_name: adrienbrignon/mkdocs-exporter
edit_uri: edit/master/docs/
site_dir: dist

validation:
  absolute_links: ignore
  unrecognized_links: ignore
  anchors: ignore

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/file-document-arrow-right
    repo: fontawesome/brands/github
  palette:
    primary: custom
    accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.prune
    - toc.follow

extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/adrienbrignon/mkdocs-exporter
    - name: PyPI
      icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-exporter

plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://installer.readthedocs.io/en/stable/objects.inv
          options:
            show_bases: false
            show_source: true
            show_labels: false
            show_root_heading: true
  - search:
      lang: en
  - awesome-pages
  - macros:
      include_dir: .
      modules:
        - macros
  - git-revision-date-localized:
      enable_creation_date: false
  - redirects:
      redirect_maps:
        'index.md': 'getting-started.md'
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        background_color: '#EA2027'
  - exporter:
      logging:
        level: debug
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, true]
          concurrency: 16
          stylesheets:
            - resources/stylesheets/pdf.scss
          covers:
            front: resources/templates/covers/front.html.j2
            back: resources/templates/covers/back.html.j2
          browser:
            debug: false
            headless: true
          aggregator:
            enabled: true
            output: documentation.pdf
            covers: limits
      buttons:
        - title: View as PDF
          icon: material-file-move-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes:
            target: _blank
            href: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.href
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_truly_sane_lists:
      truly_sane: true
      nested_indent: 2
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - assets/stylesheets/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - assets/scripts/katex.js
  - assets/scripts/mathjax.js
  - assets/scripts/mkdocs-exporter.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.min.js
