site_name: MkDocs Exporter
site_url: https://adrienbrignon.github.io/mkdocs-exporter
repo_url: https://github.com/adrienbrignon/mkdocs-exporter
repo_name: adrienbrignon/mkdocs-exporter
edit_uri: edit/master/docs/
site_dir: dist

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/file-document-arrow-right
    repo: fontawesome/brands/github
  palette:
    primary: custom
    accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow

extra:
  social:
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/adrienbrignon/mkdocs-exporter
    - name: PyPI
      icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-exporter

plugins:
  - mkdocs/exporter:
  - mkdocs/exporter/pdf:
      concurrency: 16
      stylesheets:
        - resources/stylesheets/pdf.scss
      covers:
        front: resources/templates/covers/front.html.j2
        back: resources/templates/covers/back.html.j2
  - mkdocs/exporter/extras:
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.plugins.pdf.button.enabled
          attributes:
            href: !!python/name:mkdocs_exporter.plugins.pdf.button.href
            download: !!python/name:mkdocs_exporter.plugins.pdf.button.download
  - search:
      lang: en
  - awesome-pages
  - macros:
      include_dir: .
  - git-revision-date-localized:
      enable_creation_date: false
  - redirects:
      redirect_maps:
        'index.md': 'getting-started.md'
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_truly_sane_lists:
      truly_sane: true
      nested_indent: 2
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - assets/stylesheets/custom.css
